# Generated by Django 5.0.3 on 2024-04-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('birth_Date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('user_Id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('creation_Date', models.TimeField(auto_created=True)),
                ('recipe_Name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_Level', models.FloatField()),
                ('preparation_Time', models.TimeField()),
                ('ingredients', models.TextField()),
                ('photos', models.FilePathField()),
                ('recipe_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
