# Generated by Django 5.0.3 on 2024-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='photos',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photos',
            field=models.ManyToManyField(to='api.photos'),
        ),
    ]
