# Generated by Django 5.0.3 on 2024-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photos_remove_recipe_photos_recipe_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_Level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Moderate'), (4, 'Hard'), (5, 'Chef')]),
        ),
    ]
